### PR TITLE
Fix IsItemInRange error introduced in patch 10.2.6

### PR DESCRIPTION
**Pull request by bpapuni**
Fixes [issue #212](https://github.com/Sellorio/mega-macro/issues/212)

### CODE REVIEW

**Comment by Sellorio** [comment]
Thanks for this. Could you update the TOC file to use `100206` for the wow version (just so it shows as for the current wow version). Thanks :)

**Comment by bpapuni** [comment]
Oops sorry, updated now.

**Comment by Sellorio** [comment]
Na you're all good. Thanks for doing that. I'll arrange a release as soon as I have time. Should be within 4 hours :)

**Comment by capachow** [comment]
> Na you're all good. Thanks for doing that. I'll arrange a release as soon as I have time. Should be within 4 hours :)

Please don't take this as a rush, but is there an updated ETA on the release? Been spam checking wowup every few hours, 😅. Thanks again, everyone, for you hard work on this amazing addon!

**Comment by Sellorio** [comment]
I'm sorry you're right. I'll do this right now :)

**Comment by Sellorio** [comment]
Released. Should be available any second now.

**Pull request merged**
