### PR TITLE
 feat: formatting, fixes and improvements

### LINKED ISSUE #177: Icon not working on some bars
Icon are not showing on multibar 5 6 and 7 for me.
It show the default '?' icon.
But if I move the macro to any other bar it works

### PR DESCRIPTION
**Pull request by paulbuechner**
Hey Sellorio,

I've made some fixes and improvements. I initially based the changes on @aurelion314 branch as he seemed to be maintaining the project lately. We did discuss and reviewed the changes and came to the conclusion to directly make this PR here because Mike currently doesn't has access to the game and doesn't want to block the updates I've made.

For more information on the discussion see [here](https://github.com/aurelion314/mega-macro/pull/2).

This PR includes the following features, fixes, and improvements:

Features:

- Native Macros #188 
- Updated `BlizzardActionBars` to include all available ActionBars (#177)
- Refactor EventFrame to support fixed update intervals
- Add linting support for new `known` and `unknown` conditionals (#199)
- Add UTF-8 support to parse characters

Bug Fixes:

- Temporarily disable MainMenuBar/MainActionBar tooltip to prevent: `[ADDON_ACTION_BLOCKED] AddOn 'MegaMacro' tried to call the protected function ''` (#200)
- Temporarily disable range-based hotkey coloring to prevent: #176 
- UI fixes and improvements
- Fix `channeling`/`nochanneling` modifiers

Chore:

- Formatting by: https://github.com/sumneko/lua-language-server/wiki/Formatter
- Updated TOC
- Updated README

Cheers 😊

fixes #177, #199
closes #188

### CODE REVIEW

**Comment by sellorio2** [comment]
What's the status of the temporary workarounds? Stuff that disables ranged coloring and tooltips?

**Comment by paulbuechner** [comment]
Regarding the temporary fixes, I haven't found any solution to fix them, hence "temporary fixes".

#200: This is an issue other addons experiencing too, e.g. [here](https://github.com/tullamods/Dominos/issues/701)
#176: Disabled for now

**Comment by sellorio2** [comment]
I came back to WoW today and I ran into a bug in the addon that makes it unusable so I'm testing this branch :) Switching to/from dragonflying mount completely breaks mega macro lol

**Comment by sellorio2** [comment]
Hmm the issue still exists with this version.

**Comment by paulbuechner** [comment]
> Hmm the issue still exists with this version.

In my opinion, when disabling mainbar tooltips, this is definitely happening less than before.

**Comment by sellorio2** [comment]
I'm trying to investigate the main issue (at least as far as what's blocking me from using the addon). Which is the Interface Action Blocked issue. I would love any help/info you have about it.

So far this is what I have:

* Probably triggered by an initial error.

4x [ADDON_ACTION_FORBIDDEN] AddOn 'MegaMacro' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:124: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

* After the error, activating anything on the action bar using a keybinding causes the error.
* Interstingly, the 1 slot on the action bar appears to be unaffected. I even had slot 2 working in one test for a bit til it stopped working.
* Clicking the buttons works
* Manually calling the click commands in the stub macros works
* Clearing the wow native macro's content does not stop the Blocked Interface Action popup but probably at that point the damage is done.
* Appears to be related to starting combat by using an ability bound to the Dragonflying action bar since all my tests required this to happen before the initial error and followup issues popped up.
* Short combat (one-shotting a critter) doesn't appear to be enough to trigger the issue but this is hardly definitive useful information.

**Comment by sellorio2** [comment]
Bartender4 seems to work, more testing required but it looks like until further notice this addon only works with BT4 and maybe ElvUI (although we've had support issues on there too).

**Comment by paulbuechner** [comment]
I have collected some resources of other addons suffering from similar issues, which I linked at the top:
- #200

**Comment by sellorio2** [comment]
I'm inclined to not merge this in since it will impact Bartender4 users (like myself) adversely and won't fix the critical issues with native ui.

For the range blinking. I was thinking the logic could be changed to cache the range test using the current range timer but set the action bar appearance every frame. Currently the timer controls both range test and ui changes which can cause conflicts with underlying logic.

**Comment by paulbuechner** [comment]
Sure! I agree that significant issues should be addressed at least until the next release. But if you're fine with the current features the PR is introducing, you could open a `development` branch, where we can merge this for now.

**Comment by JoeLatte88** [comment]
could some of the issue be related to GameTooltip? Went through some of the API changes which were part of 10.0.2 and beyond and noticed this in .0.2 updates:

> Tooltip Changes

<[GameTooltip](https://wowpedia.fandom.com/wiki/XML/GameTooltip)> frames no longer expose native methods for retrieving or populating tooltip contents. Instead, a new C_TooltipInfo namespace has been added which provides APIs for retrieving structured data for use in tooltips and a new set of tooltip-related mixins have been added to populate tooltips from these APIs.

https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes

**Comment by paulbuechner** [comment]
Hey @JoeLatte88, as far as I can tell these changes only apply when wanting to retrieve information from the tooltip and not when populating it. I think the API Changelog is a bit misleading there, as it states:

> "[..] a new set of tooltip-related mixins have been added to populate tooltips from these APIs."

This means, that some additional `Setters` were introduced (not that existing ones were removed)

**Pull request closed without merging**
